//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultationRoom
    {
        public decimal ID { get; set; }
        public int Status { get; set; }
        public Nullable<int> EConsultationId { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
