//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetConsultation
    {
        public PetConsultation()
        {
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Nullable<int> ConsultationId { get; set; }
        public string CustomConsultation { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Reason { get; set; }
        public bool IsDeleted { get; set; }
    
        public EncryptedText Comment { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
