//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public UserSubscription()
        {
            this.UserPermissions = new HashSet<UserPermission>();
            this.PaymentHistories = new HashSet<PaymentHistory>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public Nullable<int> SubscriptionStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public bool SubscriptionMailSent { get; set; }
        public Model.SubscriptionExpirationAlertEnum SubscriptionExpirationAlertId { get; set; }
        public Nullable<int> SubscriptionServiceID { get; set; }
        public Nullable<int> TempUserSubscriptionId { get; set; }
        public bool ispaymentDone { get; set; }
        public Nullable<bool> IsAdditionalPet { get; set; }
        public Nullable<int> AdditionalPetcount { get; set; }
    
        public virtual SubscriptionStatu SubscriptionStatu { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<PaymentHistory> PaymentHistories { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual SubscriptionExpirationAlert SubscriptionExpirationAlert { get; set; }
        public virtual SubscriptionService SubscriptionService { get; set; }
        public virtual TempUserSubscription TempUserSubscription { get; set; }
    }
}
