//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthMeasureType
    {
        public HealthMeasureType()
        {
            this.PetHealthMeasures = new HashSet<PetHealthMeasure>();
        }
    
        public Model.HealthMeasureTypeEnum Id { get; set; }
        public string Name { get; set; }
        public int HealthMeasureUnitId { get; set; }
        public Model.HealthMeasureGroupEnum HealtMeasureGroupId { get; set; }
    
        public virtual HealthMeasureGroup HealthMeasureGroup { get; set; }
        public virtual HealthMeasureUnit HealthMeasureUnit { get; set; }
        public virtual ICollection<PetHealthMeasure> PetHealthMeasures { get; set; }
    }
}
