Delete FROM [ADOPets_Rev].[dbo].[AuditLog]

Delete FROM [ADOPets_Rev].[dbo].[PetAllergy]
Delete FROM [ADOPets_Rev].[dbo].[PetCondition]
Delete FROM [ADOPets_Rev].[dbo].[PetConsultation]
Delete FROM [ADOPets_Rev].[dbo].[PetDocument]
Delete FROM [ADOPets_Rev].[dbo].[PetFoodPlan]
Delete FROM [ADOPets_Rev].[dbo].[PetHealthMeasure]
Delete FROM [ADOPets_Rev].[dbo].[PetHospitalization]
Delete FROM [ADOPets_Rev].[dbo].[PetMedication]
Delete FROM [ADOPets_Rev].[dbo].[PetSurgery]
Delete FROM [ADOPets_Rev].[dbo].[PetUser]
Delete FROM [ADOPets_Rev].[dbo].[PetVaccination]
Delete FROM [ADOPets_Rev].[dbo].[Contact]
Delete FROM [ADOPets_Rev].[dbo].[Insurance]
Delete FROM [ADOPets_Rev].[dbo].[Login]
Delete FROM [ADOPets_Rev].[dbo].[OwnerHistory]
Delete FROM [ADOPets_Rev].[dbo].[Veterinarian]

Delete FROM [ADOPets_Rev].[dbo].[Calendar]
Delete FROM [ADOPets_Rev].[dbo].[Message]
Delete FROM [ADOPets_Rev].[dbo].[PetUser]
Delete FROM [ADOPets_Rev].[dbo].[Pet]
Delete FROM [ADOPets_Rev].[dbo].[User]
Delete FROM [ADOPets_Rev].[dbo].[PaymentHistory]
Delete FROM [ADOPets_Rev].[dbo].[UserSubscription]