Insert Into [State](id,CountryId,Name,Code) Values
(53,3,'American Samoa','US-AS'),
(54,3,'District of Columbia','DC'),
(55,3,'Guam','US-GU'),
(56,3,'Northern Mariana Islands','US-MP'),
(57,3,'Puerto Rico','US-PR'),
(58,3,'South Dakota','SD'),
(59,3,'Tennessee','TN'),
(60,3,'United States Minor Outlying Islands','US-UM'),
(61,3,'Utah','UT'),
(62,3,'Vermont','VT'),
(63,3,'Virgin Islands, U.S.','US-VI'),
(64,3,'Virginia','VA'),
(65,3,'Washington','WA'),
(66,3,'West Virginia','WV'),
(67,3,'Wisconsin','WI'),
(68,3,'Wyoming','WY')
