//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EConsultation
    {
        public EConsultation()
        {
            this.EconsultationDatas = new HashSet<EconsultationData>();
            this.EconsultationMsgs = new HashSet<EconsultationMsg>();
            this.EconsultationRooms = new HashSet<EconsultationRoom>();
            this.EconsultationSummaries = new HashSet<EconsultationSummary>();
            this.EconsultationUsers = new HashSet<EconsultationUser>();
            this.EconsultDocuments = new HashSet<EconsultDocument>();
            this.EPrescriptions = new HashSet<EPrescription>();
        }
    
        public int ID { get; set; }
        public string TitleConsultation { get; set; }
        public Nullable<System.DateTime> DateConsultation { get; set; }
        public Nullable<short> TypeConsultation { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VetId { get; set; }
        public Nullable<int> PetId { get; set; }
        public Nullable<Model.EConsultationStatusEnum> EconsultationStatusId { get; set; }
        public Nullable<System.DateTime> BDateConsultation { get; set; }
        public Nullable<System.DateTime> BTimeConsultation { get; set; }
        public Nullable<System.DateTime> RDVDate { get; set; }
        public Nullable<System.DateTime> RDVDateTime { get; set; }
        public string RequestedTimeRange { get; set; }
        public string msgConsultation { get; set; }
        public Nullable<decimal> IDConversation { get; set; }
        public string VetCompID { get; set; }
        public string VetCompIP { get; set; }
        public string UserCompID { get; set; }
        public string UserCompIP { get; set; }
        public Nullable<decimal> Periods { get; set; }
        public Nullable<short> ActionFlag { get; set; }
        public Nullable<System.DateTime> ActionDateTimeBegin { get; set; }
        public Nullable<System.DateTime> ActionDateTimeEnd { get; set; }
        public string VetLocationID { get; set; }
        public Nullable<Model.TimeZoneEnum> VetTimezoneID { get; set; }
        public Nullable<decimal> VetDecalage { get; set; }
        public Nullable<int> VetDST { get; set; }
        public string UserLocationID { get; set; }
        public Nullable<Model.TimeZoneEnum> UserTimezoneID { get; set; }
        public Nullable<decimal> UserDecalage { get; set; }
        public Nullable<int> UserDST { get; set; }
        public Nullable<int> VetNotificationFlag { get; set; }
        public Nullable<System.DateTime> VetNotificationDateTime { get; set; }
        public Nullable<int> UserNotificationFlag { get; set; }
        public Nullable<System.DateTime> UserNotificationDateTime { get; set; }
        public Nullable<int> PaymentFlag { get; set; }
        public Nullable<decimal> PaymentCharged { get; set; }
        public string PaymentTransferNum { get; set; }
        public Nullable<System.DateTime> PaymentTransferDateTime { get; set; }
        public string PaymentTransferMsg { get; set; }
        public string PaymentRefNum { get; set; }
        public Nullable<int> Shared { get; set; }
        public string VerFlag { get; set; }
        public string CenterID { get; set; }
        public Nullable<Model.PaymentTypeEnum> PaymentType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string PurchaseFlag { get; set; }
        public string Survey { get; set; }
        public Nullable<Model.EConsultationContactTypeEnum> EConsultationContactTypeId { get; set; }
        public string Symptoms1 { get; set; }
        public string Symptoms2 { get; set; }
        public string Symptoms3 { get; set; }
        public string EConsultationContactValue { get; set; }
        public Nullable<Model.CountryEnum> CountryId { get; set; }
        public Nullable<int> CalenderId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsEditExpert { get; set; }
        public bool IsOwnerRead { get; set; }
    
        public virtual ICollection<EconsultationData> EconsultationDatas { get; set; }
        public virtual EConsultationContactType EConsultationContactType { get; set; }
        public virtual EConsultationStatus EConsultationStatu { get; set; }
        public virtual ICollection<EconsultationMsg> EconsultationMsgs { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual ICollection<EconsultationRoom> EconsultationRooms { get; set; }
        public virtual ICollection<EconsultationSummary> EconsultationSummaries { get; set; }
        public virtual TimeZonePet TimeZone { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EconsultationUser> EconsultationUsers { get; set; }
        public virtual TimeZonePet TimeZone1 { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual ICollection<EconsultDocument> EconsultDocuments { get; set; }
        public virtual ICollection<EPrescription> EPrescriptions { get; set; }
        public virtual Country Country { get; set; }
    }
}
