//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public Insurance()
        {
            this.AccountNumber = new EncryptedText();
            this.PlanName = new EncryptedText();
            this.Comment = new EncryptedText();
            this.GroupNumber = new EncryptedText();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Phone { get; set; }
        public bool SendNotificationMail { get; set; }
        public int PetId { get; set; }
    
        public EncryptedText AccountNumber { get; set; }
        public EncryptedText PlanName { get; set; }
        public EncryptedText Comment { get; set; }
        public EncryptedText GroupNumber { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
