//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetVaccination
    {
        public PetVaccination()
        {
            this.HospitalName = new EncryptedText();
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Nullable<int> VaccinationId { get; set; }
        public string CustomVaccination { get; set; }
        public System.DateTime InjectionDate { get; set; }
        public string SerialNumber { get; set; }
        public bool IsDeleted { get; set; }
    
        public EncryptedText HospitalName { get; set; }
        public EncryptedText Comment { get; set; }
    
        public virtual Vaccination Vaccination { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
