//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EConsultationContactType
    {
        public EConsultationContactType()
        {
            this.EConsultations = new HashSet<EConsultation>();
        }
    
        public Model.EConsultationContactTypeEnum Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EConsultation> EConsultations { get; set; }
    }
}
