//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOPets.Web.Resources.Econsultation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VeterianList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VeterianList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADOPets.Web.Resources.Econsultation.VeterianList", typeof(VeterianList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Veterinarian.
        /// </summary>
        public static string AssignVet {
            get {
                return ResourceManager.GetString("AssignVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMR.
        /// </summary>
        public static string EMR {
            get {
                return ResourceManager.GetString("EMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Veterinarian First Name.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Veterinarian Last Name.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matching Records Found.
        /// </summary>
        public static string FilterNoResult {
            get {
                return ResourceManager.GetString("FilterNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Name.
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterian.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Veterinarian.
        /// </summary>
        public static string IsCurrentVeterinarian {
            get {
                return ResourceManager.GetString("IsCurrentVeterinarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IsCurrentVeterinarianNo {
            get {
                return ResourceManager.GetString("IsCurrentVeterinarianNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IsCurrentVeterinarianYes {
            get {
                return ResourceManager.GetString("IsCurrentVeterinarianYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact.
        /// </summary>
        public static string IsEmergencyContact {
            get {
                return ResourceManager.GetString("IsEmergencyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string IsEmergencyContactNo {
            get {
                return ResourceManager.GetString("IsEmergencyContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string IsEmergencyContactYes {
            get {
                return ResourceManager.GetString("IsEmergencyContactYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Last Name.
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vet found.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}..
        /// </summary>
        public static string PagedListPagerPageCountAndCurrentLocationFormat {
            get {
                return ResourceManager.GetString("PagedListPagerPageCountAndCurrentLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing items {0} through {1} of {2}..
        /// </summary>
        public static string PagedListPagerPageItemSliceAndTotalFormat {
            get {
                return ResourceManager.GetString("PagedListPagerPageItemSliceAndTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneHome {
            get {
                return ResourceManager.GetString("PhoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Veterinarian.
        /// </summary>
        public static string SearchVet {
            get {
                return ResourceManager.GetString("SearchVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Specialty.
        /// </summary>
        public static string SpecialityPlaceHolder {
            get {
                return ResourceManager.GetString("SpecialityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StatusConfirmationCancelLabel {
            get {
                return ResourceManager.GetString("StatusConfirmationCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string StatusConfirmationOkLabel {
            get {
                return ResourceManager.GetString("StatusConfirmationOkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string StatusConfirmationTitle {
            get {
                return ResourceManager.GetString("StatusConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinarian.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinarian.
        /// </summary>
        public static string Veterinarian {
            get {
                return ResourceManager.GetString("Veterinarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VetSpecialities.
        /// </summary>
        public static string VetSpecialities {
            get {
                return ResourceManager.GetString("VetSpecialities", resourceCulture);
            }
        }
    }
}
