//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AuditLogs = new HashSet<AuditLog>();
            this.AuditLogs1 = new HashSet<AuditLog>();
            this.Calendars = new HashSet<Calendar>();
            this.Logins = new HashSet<Login>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Messages2 = new HashSet<Message>();
            this.Veterinarians = new HashSet<Veterinarian>();
            this.Pets = new HashSet<Pet>();
            this.Notifications = new HashSet<Notification>();
            this.EConsultations = new HashSet<EConsultation>();
            this.BillingInformations = new HashSet<BillingInformation>();
            this.PetContacts = new HashSet<PetContact>();
            this.SMORequests = new HashSet<SMORequest>();
            this.Contacts = new HashSet<Contact>();
            this.ShareContacts = new HashSet<ShareContact>();
            this.ShareContacts1 = new HashSet<ShareContact>();
            this.UserSubscriptionHistories = new HashSet<UserSubscriptionHistory>();
            this.SMODocuments = new HashSet<SMODocument>();
            this.ExpertBioDatas = new HashSet<ExpertBioData>();
            this.ExpertBioDatas1 = new HashSet<ExpertBioData>();
            this.SMOExpertRelations = new HashSet<SMOExpertRelation>();
            this.SMOExpertCommittees = new HashSet<SMOExpertCommittee>();
            this.SharePetInformations = new HashSet<SharePetInformation>();
            this.SharePetInformations1 = new HashSet<SharePetInformation>();
            this.SMORequests1 = new HashSet<SMORequest>();
            this.GalleryCommentReplies = new HashSet<GalleryCommentReply>();
            this.GalleryComments = new HashSet<GalleryComment>();
            this.GalleryLikes = new HashSet<GalleryLike>();
            this.SharePetInfoCommunities = new HashSet<SharePetInfoCommunity>();
            this.SharePetInfoCommunities1 = new HashSet<SharePetInfoCommunity>();
            this.FirstName = new EncryptedText();
            this.MiddleName = new EncryptedText();
            this.LastName = new EncryptedText();
            this.BirthDate = new EncryptedText();
            this.Email = new EncryptedText();
            this.PrimaryPhone = new EncryptedText();
            this.SecondaryPhone = new EncryptedText();
            this.ReferralSource = new EncryptedText();
            this.Address1 = new EncryptedText();
            this.Address2 = new EncryptedText();
            this.PostalCode = new EncryptedText();
            this.City = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Model.UserTypeEnum UserTypeId { get; set; }
        public Nullable<Model.DomainTypeEnum> DomainTypeId { get; set; }
        public Nullable<Model.TimeZoneEnum> TimeZoneId { get; set; }
        public Nullable<int> UserSubscriptionId { get; set; }
        public Nullable<Model.GenderEnum> GenderId { get; set; }
        public byte[] ProfileImage { get; set; }
        public bool GeneralConditions { get; set; }
        public Nullable<bool> IsUsingDST { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Model.UserStatusEnum UserStatusId { get; set; }
        public string InfoPath { get; set; }
        public Nullable<Model.CountryEnum> CountryId { get; set; }
        public Nullable<Model.StateEnum> StateId { get; set; }
        public bool IsNonSearchable { get; set; }
        public Nullable<int> VetDirectorID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public bool IsEmailSent { get; set; }
        public Nullable<Model.ReferralSourceEnum> ReferralSourceId { get; set; }
    
        public EncryptedText FirstName { get; set; }
        public EncryptedText MiddleName { get; set; }
        public EncryptedText LastName { get; set; }
        public EncryptedText BirthDate { get; set; }
        public EncryptedText Email { get; set; }
        public EncryptedText PrimaryPhone { get; set; }
        public EncryptedText SecondaryPhone { get; set; }
        public EncryptedText ReferralSource { get; set; }
        public EncryptedText Address1 { get; set; }
        public EncryptedText Address2 { get; set; }
        public EncryptedText PostalCode { get; set; }
        public EncryptedText City { get; set; }
    
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        public virtual ICollection<AuditLog> AuditLogs1 { get; set; }
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual Country Country { get; set; }
        public virtual DomainType DomainType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Message> Messages2 { get; set; }
        public virtual State State { get; set; }
        public virtual TimeZonePet TimeZone { get; set; }
        public virtual UserStatus UserStatu { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Veterinarian> Veterinarians { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<EConsultation> EConsultations { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
        public virtual ICollection<BillingInformation> BillingInformations { get; set; }
        public virtual ICollection<PetContact> PetContacts { get; set; }
        public virtual ICollection<SMORequest> SMORequests { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<ShareContact> ShareContacts { get; set; }
        public virtual ICollection<ShareContact> ShareContacts1 { get; set; }
        public virtual ICollection<UserSubscriptionHistory> UserSubscriptionHistories { get; set; }
        public virtual ICollection<SMODocument> SMODocuments { get; set; }
        public virtual ICollection<ExpertBioData> ExpertBioDatas { get; set; }
        public virtual ICollection<ExpertBioData> ExpertBioDatas1 { get; set; }
        public virtual ICollection<SMOExpertRelation> SMOExpertRelations { get; set; }
        public virtual ICollection<SMOExpertCommittee> SMOExpertCommittees { get; set; }
        public virtual Center Center { get; set; }
        public virtual ICollection<SharePetInformation> SharePetInformations { get; set; }
        public virtual ICollection<SharePetInformation> SharePetInformations1 { get; set; }
        public virtual ICollection<SMORequest> SMORequests1 { get; set; }
        public virtual ICollection<GalleryCommentReply> GalleryCommentReplies { get; set; }
        public virtual ICollection<GalleryComment> GalleryComments { get; set; }
        public virtual ICollection<GalleryLike> GalleryLikes { get; set; }
        public virtual ICollection<SharePetInfoCommunity> SharePetInfoCommunities { get; set; }
        public virtual ICollection<SharePetInfoCommunity> SharePetInfoCommunities1 { get; set; }
        public virtual ReferralSource ReferralSource1 { get; set; }
    }
}
