//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Model;
    
    public partial class ADOPetsEntities : DbContext
    {
        public ADOPetsEntities()
            : base("name=ADOPetsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Allergy> Allergies { get; set; }
        public DbSet<AuditModificationType> AuditModificationTypes { get; set; }
        public DbSet<Consultation> Consultations { get; set; }
        public DbSet<Customization> Customizations { get; set; }
        public DbSet<DocumentSubType> DocumentSubTypes { get; set; }
        public DbSet<DocumentType> DocumentTypes { get; set; }
        public DbSet<DomainType> DomainTypes { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<HairType> HairTypes { get; set; }
        public DbSet<Medication> Medications { get; set; }
        public DbSet<Partner> Partners { get; set; }
        public DbSet<PartnerSubscription> PartnerSubscriptions { get; set; }
        public DbSet<PartnerType> PartnerTypes { get; set; }
        public DbSet<Pathology> Pathologies { get; set; }
        public DbSet<PetDocument> PetDocuments { get; set; }
        public DbSet<PetFoodPlan> PetFoodPlans { get; set; }
        public DbSet<PetGroupType> PetGroupTypes { get; set; }
        public DbSet<PetStatus> PetStatus1 { get; set; }
        public DbSet<PetSurgery> PetSurgeries { get; set; }
        public DbSet<PetType> PetTypes { get; set; }
        public DbSet<SubscriptionStatu> SubscriptionStatus { get; set; }
        public DbSet<Surgery> Surgeries { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<UserStatus> UserStatus1 { get; set; }
        public DbSet<UserSubscription> UserSubscriptions { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<Vaccination> Vaccinations { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<BreedType> BreedTypes { get; set; }
        public DbSet<BloodGroupType> BloodGroupTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<HealthMeasureGroup> HealthMeasureGroups { get; set; }
        public DbSet<HealthMeasureType> HealthMeasureTypes { get; set; }
        public DbSet<HealthMeasureUnit> HealthMeasureUnits { get; set; }
        public DbSet<MedicationStatus> MedicationStatus1 { get; set; }
        public DbSet<PetHospitalization> PetHospitalizations { get; set; }
        public DbSet<PetAllergy> PetAllergies { get; set; }
        public DbSet<PetMedication> PetMedications { get; set; }
        public DbSet<PetHealthMeasure> PetHealthMeasures { get; set; }
        public DbSet<PetConsultation> PetConsultations { get; set; }
        public DbSet<Insurance> Insurances { get; set; }
        public DbSet<Veterinarian> Veterinarians { get; set; }
        public DbSet<PetVaccination> PetVaccinations { get; set; }
        public DbSet<ContactType> ContactTypes { get; set; }
        public DbSet<PetCondition> PetConditions { get; set; }
        public DbSet<Farmer> Farmers { get; set; }
        public DbSet<Pet> Pets { get; set; }
        public DbSet<PaymentHistory> PaymentHistories { get; set; }
        public DbSet<TransactionResult> TransactionResults { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<CreditCardType> CreditCardTypes { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<TimeZonePet> TimeZonePets { get; set; }
        public DbSet<BillingInformation> BillingInformations { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<EconsultationData> EconsultationDatas { get; set; }
        public DbSet<EconsultationMsg> EconsultationMsgs { get; set; }
        public DbSet<EconsultationRoom> EconsultationRooms { get; set; }
        public DbSet<EconsultationSummary> EconsultationSummaries { get; set; }
        public DbSet<EconsultationUser> EconsultationUsers { get; set; }
        public DbSet<NotificationType> NotificationTypes { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<EConsultationStatus> EConsultationStatus1 { get; set; }
        public DbSet<EConsultation> EConsultations { get; set; }
        public DbSet<EConsultationContactType> EConsultationContactTypes { get; set; }
        public DbSet<SMOInvestigation> SMOInvestigations { get; set; }
        public DbSet<SMORequest> SMORequests { get; set; }
        public DbSet<SMORequestStatu> SMORequestStatus { get; set; }
        public DbSet<PetContact> PetContacts { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<VetSpeciality> VetSpecialities { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<AlbumGallery> AlbumGalleries { get; set; }
        public DbSet<ShareCategoryType> ShareCategoryTypes { get; set; }
        public DbSet<ShareContact> ShareContacts { get; set; }
        public DbSet<VideoGallery> VideoGalleries { get; set; }
        public DbSet<SMOOwnerRequestStatu> SMOOwnerRequestStatus { get; set; }
        public DbSet<SubscriptionExpirationAlert> SubscriptionExpirationAlerts { get; set; }
        public DbSet<SubscriptionService> SubscriptionServices { get; set; }
        public DbSet<UserSubscriptionHistory> UserSubscriptionHistories { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<AlbumGallery_Photo> AlbumGallery_Photo { get; set; }
        public DbSet<SMODocument> SMODocuments { get; set; }
        public DbSet<ExpertBioData> ExpertBioDatas { get; set; }
        public DbSet<SMOExpertRelation> SMOExpertRelations { get; set; }
        public DbSet<SMOExpertCommittee> SMOExpertCommittees { get; set; }
        public DbSet<EconsultDocument> EconsultDocuments { get; set; }
        public DbSet<EPrescription> EPrescriptions { get; set; }
        public DbSet<TempUserSubscription> TempUserSubscriptions { get; set; }
        public DbSet<Center> Centers { get; set; }
        public DbSet<ShareCategoryTypeContact> ShareCategoryTypeContacts { get; set; }
        public DbSet<SharePetInformation> SharePetInformations { get; set; }
        public DbSet<GalleryCommentReply> GalleryCommentReplies { get; set; }
        public DbSet<GalleryComment> GalleryComments { get; set; }
        public DbSet<GalleryLike> GalleryLikes { get; set; }
        public DbSet<SharePetInfoCommunity> SharePetInfoCommunities { get; set; }
        public DbSet<ReferralSource> ReferralSources { get; set; }
        public DbSet<PetGender> PetGenders { get; set; }
        public DbSet<PlanType> PlanTypes { get; set; }
        public DbSet<PlanFeature> PlanFeatures { get; set; }
    }
}
