//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOPets.Web.Resources.Econsultation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADOPets.Web.Resources.Econsultation.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string Datetime {
            get {
                return ResourceManager.GetString("Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display.
        /// </summary>
        public static string Econsultation_Index_NoRecordFound {
            get {
                return ResourceManager.GetString("Econsultation_Index_NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matching Records Found.
        /// </summary>
        public static string FilterNoResult {
            get {
                return ResourceManager.GetString("FilterNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewEconsultation {
            get {
                return ResourceManager.GetString("NewEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matching Records Found.
        /// </summary>
        public static string Pet_Index_FilterNoResult {
            get {
                return ResourceManager.GetString("Pet_Index_FilterNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EC found.
        /// </summary>
        public static string Pet_Index_NoRecords {
            get {
                return ResourceManager.GetString("Pet_Index_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}..
        /// </summary>
        public static string Pet_Index_PagedListPagerPageCountAndCurrentLocationFormat {
            get {
                return ResourceManager.GetString("Pet_Index_PagedListPagerPageCountAndCurrentLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing items {0} through {1} of {2}..
        /// </summary>
        public static string Pet_Index_PagedListPagerPageItemSliceAndTotalFormat {
            get {
                return ResourceManager.GetString("Pet_Index_PagedListPagerPageItemSliceAndTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PetName {
            get {
                return ResourceManager.GetString("PetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Type.
        /// </summary>
        public static string PetType {
            get {
                return ResourceManager.GetString("PetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Pet Name.
        /// </summary>
        public static string SearchByPetNamePlaceHolder {
            get {
                return ResourceManager.GetString("SearchByPetNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Status.
        /// </summary>
        public static string SearchByStatusPlaceHolder {
            get {
                return ResourceManager.GetString("SearchByStatusPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Consultation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string VetSpeciality {
            get {
                return ResourceManager.GetString("VetSpeciality", resourceCulture);
            }
        }
    }
}
