//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareContact
    {
        public ShareContact()
        {
            this.ShareCategoryTypeContacts = new HashSet<ShareCategoryTypeContact>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ContactId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ShareCategoryTypeContact> ShareCategoryTypeContacts { get; set; }
    }
}
