//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryCommentReply
    {
        public int Id { get; set; }
        public int CommentId { get; set; }
        public string Comment { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual GalleryComment GalleryComment { get; set; }
        public virtual User User { get; set; }
    }
}
