//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetHealthMeasure
    {
        public int Id { get; set; }
        public int PetId { get; set; }
        public Model.HealthMeasureTypeEnum HealthMeasureTypeId { get; set; }
        public string MeasureValue { get; set; }
        public string MeasureValueExtra { get; set; }
        public System.DateTime MeasuredDate { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual HealthMeasureType HealthMeasureType { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
