//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetDocument
    {
        public PetDocument()
        {
            this.DocumentName = new EncryptedText();
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Model.DocumentSubTypeEnum DocumentSubTypeId { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DocumentPath { get; set; }
    
        public EncryptedText DocumentName { get; set; }
        public EncryptedText Comment { get; set; }
    
        public virtual DocumentSubType DocumentSubType { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
