INSERT INTO [ADOPets_Rev].[dbo].[State] Values (13, 3, 'AL', 'Alabama')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (14, 3, 'AK', 'Alaska')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (15, 3, 'AZ', 'Arizona')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (16, 3, 'AR', 'Arkansas')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (18, 3, 'CO', 'Colorado')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (19, 3, 'CT', 'Connecticut')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (20, 3, 'DE', 'Delaware')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (21, 3, 'FL', 'Florida')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (22, 3, 'GA', 'Georgia')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (23, 3, 'HI', 'Hawaii')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (24, 3, 'ID', 'Idaho')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (25, 3, 'IL', 'Illinois')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (26, 3, 'IN', 'Indiana')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (27, 3, 'IA', 'Iowa')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (28, 3, 'KS', 'Kansas')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (29, 3, 'KY', 'Kentucky')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (30, 3, 'LA', 'Louisiana')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (31, 3, 'ME', 'Maine')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (32, 3, 'MD', 'Maryland')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (33, 3, 'MA', 'Massachusetts')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (34, 3, 'MI', 'Michigan')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (35, 3, 'MN', 'Minnesota')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (36, 3, 'MS', 'Mississippi')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (37, 3, 'MO', 'Missouri')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (38, 3, 'MT', 'Montana')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (39, 3, 'NE', 'Nebraska')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (40, 3, 'NV', 'Nevada')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (41, 3, 'NH', 'New Hampshire')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (42, 3, 'NJ', 'New Jersey')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (43, 3, 'M', 'New Mexico')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (45, 3, 'NC', 'North Carolina')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (46, 3, 'ND', 'North Dakota')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (47, 3, 'OH', 'Ohio')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (48, 3, 'OK', 'Oklahoma')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (49, 3, 'OR', 'Oregon')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (50, 3, 'PA', 'Pennsylvania')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (51, 3, 'RI', 'Rhode Island')
INSERT INTO [ADOPets_Rev].[dbo].[State] Values (52, 3, 'SC', 'South Carolina')
