//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMOInvestigation
    {
        public long ID { get; set; }
        public Nullable<long> SMORequestID { get; set; }
        public string TestType { get; set; }
        public string TestDescription { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
    
        public virtual SMORequest SMORequest { get; set; }
    }
}
