//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscriptionHistory
    {
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime RenewvalDate { get; set; }
        public Nullable<bool> SubscriptionMailSent { get; set; }
        public Nullable<Model.SubscriptionExpirationAlertEnum> SubscriptionExpirationAlertId { get; set; }
        public Nullable<int> AditionalPetCount { get; set; }
        public Nullable<int> AditionalSMOCount { get; set; }
        public Nullable<int> AditionalMRACount { get; set; }
        public Nullable<int> AditionalECCount { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime UsedDate { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual SubscriptionExpirationAlert SubscriptionExpirationAlert { get; set; }
        public virtual User User { get; set; }
    }
}
