//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInformation
    {
        public BillingInformation()
        {
            this.PaymentHistories = new HashSet<PaymentHistory>();
        }
    
        public int Id { get; set; }
        public Model.PaymentTypeEnum PaymentTypeId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Model.CountryEnum CountryId { get; set; }
        public Nullable<Model.StateEnum> StateId { get; set; }
        public string Zip { get; set; }
        public Nullable<Model.CreditCardTypeEnum> CreditCardTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<PaymentHistory> PaymentHistories { get; set; }
        public virtual User User { get; set; }
    }
}
