//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreedType
    {
        public BreedType()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public Model.BreedTypeEnum Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Information { get; set; }
        public Nullable<bool> IsDangerous { get; set; }
    
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
