//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.EConsultations = new HashSet<EConsultation>();
            this.Reason = new EncryptedText();
            this.Physician = new EncryptedText();
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PetId { get; set; }
        public bool SendNotificationMail { get; set; }
        public bool NotificationSent { get; set; }
        public bool IsRead { get; set; }
    
        public EncryptedText Reason { get; set; }
        public EncryptedText Physician { get; set; }
        public EncryptedText Comment { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EConsultation> EConsultations { get; set; }
    }
}
