//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubType
    {
        public DocumentSubType()
        {
            this.PetDocuments = new HashSet<PetDocument>();
            this.SMODocuments = new HashSet<SMODocument>();
            this.EconsultDocuments = new HashSet<EconsultDocument>();
        }
    
        public Model.DocumentSubTypeEnum Id { get; set; }
        public string Name { get; set; }
        public int DocumentTypeId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<PetDocument> PetDocuments { get; set; }
        public virtual ICollection<SMODocument> SMODocuments { get; set; }
        public virtual ICollection<EconsultDocument> EconsultDocuments { get; set; }
    }
}
