//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultationMsg
    {
        public decimal ID { get; set; }
        public Nullable<int> EConsultationId { get; set; }
        public Nullable<int> EconsultationRoomId { get; set; }
        public string MsgSender { get; set; }
        public string MsgContent { get; set; }
        public Nullable<System.DateTime> MsgDateTime { get; set; }
        public byte[] MsgTime { get; set; }
        public string MsgIP { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string Msgrq { get; set; }
        public string Msgsj { get; set; }
        public string DateTimeGMT { get; set; }
        public string TimeD { get; set; }
        public string TimeE { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
