//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultDocument
    {
        public int Id { get; set; }
        public int EcId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<Model.DocumentSubTypeEnum> DocumentSubTypeId { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
        public virtual DocumentSubType DocumentSubType { get; set; }
    }
}
