//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultationUser
    {
        public decimal ID { get; set; }
        public Nullable<int> EConsultationId { get; set; }
        public Nullable<int> EconsultationRoomID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> LastMsgActivity { get; set; }
        public Nullable<System.DateTime> LastVideoActivity { get; set; }
        public byte[] LastActivity { get; set; }
        public Nullable<int> UserStatus { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
