//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmer
    {
        public Farmer()
        {
            this.Pets = new HashSet<Pet>();
            this.PhoneHome = new EncryptedText();
            this.PhoneOffice = new EncryptedText();
            this.PhoneCell = new EncryptedText();
            this.Fax = new EncryptedText();
            this.Email = new EncryptedText();
            this.Zip = new EncryptedText();
            this.Address1 = new EncryptedText();
            this.Address2 = new EncryptedText();
            this.Name = new EncryptedText();
            this.City = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Nullable<Model.CountryEnum> CountryId { get; set; }
        public Nullable<Model.StateEnum> StateId { get; set; }
    
        public EncryptedText PhoneHome { get; set; }
        public EncryptedText PhoneOffice { get; set; }
        public EncryptedText PhoneCell { get; set; }
        public EncryptedText Fax { get; set; }
        public EncryptedText Email { get; set; }
        public EncryptedText Zip { get; set; }
        public EncryptedText Address1 { get; set; }
        public EncryptedText Address2 { get; set; }
        public EncryptedText Name { get; set; }
        public EncryptedText City { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
