//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Model.NotificationTypeEnum NotificationTypeId { get; set; }
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime Date { get; set; }
        public bool Succeed { get; set; }
        public string ErrorMessage { get; set; }
        public string ExtraValue { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
