//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSubscription
    {
        public int PartnerId { get; set; }
        public int SubscriptionId { get; set; }
        public string PromotionCode { get; set; }
        public int SubscriptionStatusId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual SubscriptionStatu SubscriptionStatu { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
