//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Pet()
        {
            this.AuditLogs = new HashSet<AuditLog>();
            this.Insurances = new HashSet<Insurance>();
            this.PetMedications = new HashSet<PetMedication>();
            this.PetAllergies = new HashSet<PetAllergy>();
            this.PetConditions = new HashSet<PetCondition>();
            this.PetConsultations = new HashSet<PetConsultation>();
            this.PetFoodPlans = new HashSet<PetFoodPlan>();
            this.PetHospitalizations = new HashSet<PetHospitalization>();
            this.PetVaccinations = new HashSet<PetVaccination>();
            this.PetDocuments = new HashSet<PetDocument>();
            this.PetHealthMeasures = new HashSet<PetHealthMeasure>();
            this.PetSurgeries = new HashSet<PetSurgery>();
            this.Veterinarians = new HashSet<Veterinarian>();
            this.Calendars = new HashSet<Calendar>();
            this.Users = new HashSet<User>();
            this.EConsultations = new HashSet<EConsultation>();
            this.SMORequests = new HashSet<SMORequest>();
            this.PetContacts = new HashSet<PetContact>();
            this.Galleries = new HashSet<Gallery>();
            this.Contacts = new HashSet<Contact>();
            this.VideoGalleries = new HashSet<VideoGallery>();
            this.AlbumGalleries = new HashSet<AlbumGallery>();
            this.SharePetInformations = new HashSet<SharePetInformation>();
            this.ShareCategoryTypeContacts = new HashSet<ShareCategoryTypeContact>();
            this.SharePetInfoCommunities = new HashSet<SharePetInfoCommunity>();
            this.Name = new EncryptedText();
            this.TattooNumber = new EncryptedText();
            this.PlaceOfBirth = new EncryptedText();
            this.Zip = new EncryptedText();
            this.ChipNumber = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Model.PetTypeEnum PetTypeId { get; set; }
        public Nullable<Model.BloodGroupTypeEnum> BloodGroupTypeId { get; set; }
        public Nullable<Model.HairTypeEnum> HairTypeId { get; set; }
        public string CustomHairType { get; set; }
        public Nullable<Model.BreedTypeEnum> BreedTypeId { get; set; }
        public string CustomBreed { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<Model.PetGenderEnum> GenderId { get; set; }
        public Nullable<Model.ColorEnum> ColorId { get; set; }
        public string CustomColor { get; set; }
        public string Pedigree { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsSterile { get; set; }
        public Nullable<Model.CountryEnum> CountryOfBirthId { get; set; }
        public Nullable<Model.StateEnum> StateOfBirthId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Model.PetStatusEnum PetStatusId { get; set; }
        public bool IsDeleted { get; set; }
        public string CoverImage { get; set; }
        public string SecondaryBreed { get; set; }
        public Nullable<System.DateTime> AdoptionDate { get; set; }
    
        public EncryptedText Name { get; set; }
        public EncryptedText TattooNumber { get; set; }
        public EncryptedText PlaceOfBirth { get; set; }
        public EncryptedText Zip { get; set; }
        public EncryptedText ChipNumber { get; set; }
    
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        public virtual BloodGroupType BloodGroupType { get; set; }
        public virtual BreedType BreedType { get; set; }
        public virtual Color Color { get; set; }
        public virtual Country Country { get; set; }
        public virtual Farmer Farmer { get; set; }
        public virtual HairType HairType { get; set; }
        public virtual ICollection<Insurance> Insurances { get; set; }
        public virtual ICollection<PetMedication> PetMedications { get; set; }
        public virtual ICollection<PetAllergy> PetAllergies { get; set; }
        public virtual ICollection<PetCondition> PetConditions { get; set; }
        public virtual ICollection<PetConsultation> PetConsultations { get; set; }
        public virtual ICollection<PetFoodPlan> PetFoodPlans { get; set; }
        public virtual ICollection<PetHospitalization> PetHospitalizations { get; set; }
        public virtual ICollection<PetVaccination> PetVaccinations { get; set; }
        public virtual State State { get; set; }
        public virtual PetStatus PetStatu { get; set; }
        public virtual ICollection<PetDocument> PetDocuments { get; set; }
        public virtual ICollection<PetHealthMeasure> PetHealthMeasures { get; set; }
        public virtual PetType PetType { get; set; }
        public virtual ICollection<PetSurgery> PetSurgeries { get; set; }
        public virtual ICollection<Veterinarian> Veterinarians { get; set; }
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<EConsultation> EConsultations { get; set; }
        public virtual ICollection<SMORequest> SMORequests { get; set; }
        public virtual ICollection<PetContact> PetContacts { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<VideoGallery> VideoGalleries { get; set; }
        public virtual ICollection<AlbumGallery> AlbumGalleries { get; set; }
        public virtual ICollection<SharePetInformation> SharePetInformations { get; set; }
        public virtual ICollection<ShareCategoryTypeContact> ShareCategoryTypeContacts { get; set; }
        public virtual ICollection<SharePetInfoCommunity> SharePetInfoCommunities { get; set; }
        public virtual PetGender PetGender { get; set; }
    }
}
