//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetAllergy
    {
        public PetAllergy()
        {
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Nullable<int> AllergyId { get; set; }
        public string CustomAllergy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Reaction { get; set; }
        public bool IsDeleted { get; set; }
    
        public EncryptedText Comment { get; set; }
    
        public virtual Allergy Allergy { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
