//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetMedication
    {
        public PetMedication()
        {
            this.Physician = new EncryptedText();
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Nullable<int> MedicationId { get; set; }
        public string CustomMedication { get; set; }
        public string Reason { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<Model.MedicationStatusEnum> MedicationStatusId { get; set; }
        public int Duration { get; set; }
        public string Dosage { get; set; }
        public string Route { get; set; }
        public bool SendReminderMail { get; set; }
        public bool IsDeleted { get; set; }
        public string Frequency { get; set; }
    
        public EncryptedText Physician { get; set; }
        public EncryptedText Comment { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual MedicationStatus MedicationStatu { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
