//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetSurgery
    {
        public PetSurgery()
        {
            this.Physician = new EncryptedText();
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public Nullable<Model.SurgeryEnum> SurgeryId { get; set; }
        public string CustomSurgery { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public string Reason { get; set; }
        public bool IsDeleted { get; set; }
    
        public EncryptedText Physician { get; set; }
        public EncryptedText Comment { get; set; }
    
        public virtual Surgery Surgery { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
