//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFeature
    {
        public int Id { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public bool IsPetIDInformation { get; set; }
        public bool IsEmergencyContact { get; set; }
        public bool IsVetInformation { get; set; }
        public bool IsMessage { get; set; }
        public bool IsCalendar { get; set; }
        public bool IsReminder { get; set; }
        public bool IsPhotoGallery { get; set; }
        public bool IsPetShare { get; set; }
        public bool IsHealthHistory { get; set; }
        public bool IsHealthMeasureTracker { get; set; }
        public bool IsMedicalDocument { get; set; }
        public bool IsMRA { get; set; }
        public bool IsSMO { get; set; }
        public bool IsEC { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
