//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharePetInformation
    {
        public int Id { get; set; }
        public Model.ShareCategoryTypeEnum ShareCategoryTypeId { get; set; }
        public int ContactId { get; set; }
        public int PetId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual ShareCategoryType ShareCategoryType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
