//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMODocument
    {
        public SMODocument()
        {
            this.DocumentName = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Nullable<long> SMOId { get; set; }
        public Nullable<Model.DocumentSubTypeEnum> DocumentSubTypeId { get; set; }
        public string DocumentPath { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public EncryptedText DocumentName { get; set; }
    
        public virtual DocumentSubType DocumentSubType { get; set; }
        public virtual SMORequest SMORequest { get; set; }
        public virtual User User { get; set; }
    }
}
