//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMOExpertCommittee
    {
        public int Id { get; set; }
        public Nullable<int> VeterinaryExpertId { get; set; }
        public Nullable<long> SMORequestId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual SMORequest SMORequest { get; set; }
        public virtual User User { get; set; }
    }
}
