//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMOExpertRelation
    {
        public long ID { get; set; }
        public Nullable<long> SMORequestID { get; set; }
        public Nullable<int> VetExpertID { get; set; }
        public Nullable<System.DateTime> AssingedDate { get; set; }
        public string ExpertResponse { get; set; }
        public bool IsRead { get; set; }
        public bool IsFinal { get; set; }
    
        public virtual SMORequest SMORequest { get; set; }
        public virtual User User { get; set; }
    }
}
