//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMORequest
    {
        public SMORequest()
        {
            this.SMOInvestigations = new HashSet<SMOInvestigation>();
            this.SMODocuments = new HashSet<SMODocument>();
            this.SMOExpertRelations = new HashSet<SMOExpertRelation>();
            this.SMOExpertCommittees = new HashSet<SMOExpertCommittee>();
            this.Diagnosis = new EncryptedText();
            this.Comments = new EncryptedText();
            this.FirstOpinion = new EncryptedText();
            this.Question = new EncryptedText();
            this.Symptoms2 = new EncryptedText();
            this.Symptoms3 = new EncryptedText();
            this.VetComment = new EncryptedText();
            this.Symptoms1 = new EncryptedText();
        }
    
        public long ID { get; set; }
        public Nullable<int> PetId { get; set; }
        public Nullable<System.DateTime> DateOfOnSet { get; set; }
        public Nullable<Model.SMORequestStatusEnum> SMORequestStatusId { get; set; }
        public Nullable<System.DateTime> ValidatedOn { get; set; }
        public Nullable<System.DateTime> ClosedOn { get; set; }
        public Nullable<bool> InCompleteMedicalRecord { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string RequestReason { get; set; }
        public string MedicalHistoryComment { get; set; }
        public string AdditionalInformation { get; set; }
        public Nullable<int> SMOSubmittedBy { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public bool IsRead { get; set; }
        public bool IsOwnerRead { get; set; }
        public bool IsSMOPaymentDone { get; set; }
    
        public EncryptedText Diagnosis { get; set; }
        public EncryptedText Comments { get; set; }
        public EncryptedText FirstOpinion { get; set; }
        public EncryptedText Question { get; set; }
        public EncryptedText Symptoms2 { get; set; }
        public EncryptedText Symptoms3 { get; set; }
        public EncryptedText VetComment { get; set; }
        public EncryptedText Symptoms1 { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual ICollection<SMOInvestigation> SMOInvestigations { get; set; }
        public virtual SMORequestStatu SMORequestStatu { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SMODocument> SMODocuments { get; set; }
        public virtual ICollection<SMOExpertRelation> SMOExpertRelations { get; set; }
        public virtual ICollection<SMOExpertCommittee> SMOExpertCommittees { get; set; }
        public virtual User User1 { get; set; }
    }
}
