//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionExpirationAlert
    {
        public SubscriptionExpirationAlert()
        {
            this.UserSubscriptions = new HashSet<UserSubscription>();
            this.UserSubscriptionHistories = new HashSet<UserSubscriptionHistory>();
        }
    
        public Model.SubscriptionExpirationAlertEnum Id { get; set; }
        public string Name { get; set; }
        public int DaysBefore { get; set; }
    
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
        public virtual ICollection<UserSubscriptionHistory> UserSubscriptionHistories { get; set; }
    }
}
