//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserSubscription
    {
        public TempUserSubscription()
        {
            this.UserSubscriptions = new HashSet<UserSubscription>();
        }
    
        public int Id { get; set; }
        public int SubscriptionId { get; set; }
        public Nullable<int> SubscriptionStatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public bool SubscriptionMailSent { get; set; }
        public int SubscriptionExpirationAlertId { get; set; }
        public Nullable<int> AditionalPetCount { get; set; }
        public Nullable<int> AditionalSMOCount { get; set; }
        public Nullable<int> AditionalMRACount { get; set; }
        public Nullable<int> AditionalECCount { get; set; }
        public bool ispaymentDone { get; set; }
        public bool isCreatedbyOwner { get; set; }
        public string actionName { get; set; }
        public string deletedPetsID { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual SubscriptionStatu SubscriptionStatu { get; set; }
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
    }
}
