//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZonePet
    {
        public TimeZonePet()
        {
            this.Users = new HashSet<User>();
            this.EConsultations = new HashSet<EConsultation>();
            this.EConsultations1 = new HashSet<EConsultation>();
        }
    
        public Model.TimeZoneEnum Id { get; set; }
        public string Name { get; set; }
        public string TimeZoneInfoId { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<EConsultation> EConsultations { get; set; }
        public virtual ICollection<EConsultation> EConsultations1 { get; set; }
    }
}
