//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int UserId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> UserSubscriptionId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
    }
}
