//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultationData
    {
        public decimal ID { get; set; }
        public Nullable<int> EConsultationId { get; set; }
        public string VeterianBrowser { get; set; }
        public string UserBrowser { get; set; }
        public string VeterianDevice { get; set; }
        public string UserDevice { get; set; }
        public string VeterianAudio { get; set; }
        public string UserAudio { get; set; }
        public string VeterianVideo { get; set; }
        public string UserVideo { get; set; }
        public string Survey { get; set; }
        public Nullable<bool> FlagRecord { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
