//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOPets.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subscription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subscription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADOPets.Web.Resources.Subscription", typeof(Subscription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per additional pet, with {1} MRA.
        /// </summary>
        public static string PlanDescWithMRA {
            get {
                return ResourceManager.GetString("PlanDescWithMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per additional pet, with {1} MRA and {2} SMO.
        /// </summary>
        public static string PlanDescWithMRAWithSMO {
            get {
                return ResourceManager.GetString("PlanDescWithMRAWithSMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per additional pet.
        /// </summary>
        public static string PlanDescWithoutMRA {
            get {
                return ResourceManager.GetString("PlanDescWithoutMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per additional pet, with {1} SMO.
        /// </summary>
        public static string PlanDescWithSMO {
            get {
                return ResourceManager.GetString("PlanDescWithSMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pets, which includes {2} MRA.
        /// </summary>
        public static string PlanWithMRA {
            get {
                return ResourceManager.GetString("PlanWithMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pets, which includes {2} MRA and {3} SMO.
        /// </summary>
        public static string PlanWithMRAWithSMO {
            get {
                return ResourceManager.GetString("PlanWithMRAWithSMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pets.
        /// </summary>
        public static string PlanWithoutMRA {
            get {
                return ResourceManager.GetString("PlanWithoutMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pets, which includes {2} SMO.
        /// </summary>
        public static string PlanWithSMO {
            get {
                return ResourceManager.GetString("PlanWithSMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pet, which includes {2} MRA.
        /// </summary>
        public static string SinglePlanWithMRA {
            get {
                return ResourceManager.GetString("SinglePlanWithMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pet, which includes {2} MRA and {3} SMO.
        /// </summary>
        public static string SinglePlanWithMRAWithSMO {
            get {
                return ResourceManager.GetString("SinglePlanWithMRAWithSMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pet.
        /// </summary>
        public static string SinglePlanWithoutMRA {
            get {
                return ResourceManager.GetString("SinglePlanWithoutMRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${0} per year for {1} pet, which includes {2} SMO.
        /// </summary>
        public static string SinglePlanWithSMO {
            get {
                return ResourceManager.GetString("SinglePlanWithSMO", resourceCulture);
            }
        }
    }
}
