//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.FirstName = new EncryptedText();
            this.MiddleName = new EncryptedText();
            this.LastName = new EncryptedText();
            this.Email = new EncryptedText();
            this.PhoneCell = new EncryptedText();
            this.PhoneOffice = new EncryptedText();
            this.PhoneHome = new EncryptedText();
            this.Fax = new EncryptedText();
        }
    
        public int Id { get; set; }
        public Model.ContactTypeEnum ContactTypeId { get; set; }
        public bool IsEmergencyContact { get; set; }
        public int UserId { get; set; }
        public Nullable<int> VeterinarianId { get; set; }
        public Nullable<int> PetContactId { get; set; }
        public Nullable<int> PetId { get; set; }
    
        public EncryptedText FirstName { get; set; }
        public EncryptedText MiddleName { get; set; }
        public EncryptedText LastName { get; set; }
        public EncryptedText Email { get; set; }
        public EncryptedText PhoneCell { get; set; }
        public EncryptedText PhoneOffice { get; set; }
        public EncryptedText PhoneHome { get; set; }
        public EncryptedText Fax { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual PetContact PetContact { get; set; }
        public virtual User User { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
