use ADOPets_Rev

alter table TimeZone
add TimeZoneInfoId nvarchar (max)
Go

alter table TimeZone
drop column Description
Go

UPDATE [User]
SET [TimeZoneId] = NULL

Delete From TimeZone

DBCC CHECKIDENT('TimeZone', RESEED, 0)


INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-12:00) International Date Line West', 'Dateline Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-11:00) Coordinated Universal Time-11', 'UTC-11')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-10:00) Hawaii', 'Hawaiian Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-09:00) Alaska', 'Alaskan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-08:00) Baja California', 'Pacific Standard Time (Mexico)')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-08:00) Pacific Time (US & Canada)', 'Pacific Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-07:00) Arizona', 'US Mountain Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-07:00) Chihuahua, La Paz, Mazatlan', 'Mountain Standard Time (Mexico)')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-07:00) Mountain Time (US & Canada)', 'Mountain Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-06:00) Central America', 'Central America Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-06:00) Central Time (US & Canada)', 'Central Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-06:00) Guadalajara, Mexico City, Monterrey', 'Central Standard Time (Mexico)')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-06:00) Saskatchewan', 'Canada Central Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-05:00) Bogota, Lima, Quito, Rio Branco', 'SA Pacific Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-05:00) Eastern Time (US & Canada)', 'Eastern Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-05:00) Indiana (East)', 'US Eastern Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:30) Caracas', 'Venezuela Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:00) Asuncion', 'Paraguay Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:00) Atlantic Time (Canada)', 'Atlantic Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:00) Cuiaba', 'Central Brazilian Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan', 'SA Western Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-04:00) Santiago', 'Pacific SA Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:30) Newfoundland', 'Newfoundland Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Brasilia', 'E. South America Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Buenos Aires', 'Argentina Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Cayenne, Fortaleza', 'SA Eastern Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Greenland', 'Greenland Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Montevideo', 'Montevideo Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-03:00) Salvador', 'Bahia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-02:00) Coordinated Universal Time-02', 'UTC-02')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-02:00) Mid-Atlantic - Old', 'Mid-Atlantic Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-01:00) Azores', 'Azores Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC-01:00) Cape Verde Is.', 'Cape Verde Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC) Casablanca', 'Morocco Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC) Coordinated Universal Time', 'UTC')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC) Dublin, Edinburgh, Lisbon, London', 'GMT Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC) Monrovia, Reykjavik', 'Greenwich Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', 'W. Europe Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', 'Central Europe Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', 'Romance Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb', 'Central European Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) West Central Africa', 'W. Central Africa Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+01:00) Windhoek', 'Namibia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Amman', 'Jordan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Athens, Bucharest', 'GTB Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Beirut', 'Middle East Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Cairo', 'Egypt Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Damascus', 'Syria Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) E. Europe', 'E. Europe Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Harare, Pretoria', 'South Africa Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', 'FLE Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Istanbul', 'Turkey Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Jerusalem', 'Israel Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+02:00) Tripoli', 'Libya Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+03:00) Baghdad', 'Arabic Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+03:00) Kaliningrad, Minsk', 'Kaliningrad Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+03:00) Kuwait, Riyadh', 'Arab Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+03:00) Nairobi', 'E. Africa Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+03:30) Tehran', 'Iran Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Abu Dhabi, Muscat', 'Arabian Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Baku', 'Azerbaijan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Moscow, St. Petersburg, Volgograd', 'Russian Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Port Louis', 'Mauritius Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Tbilisi', 'Georgian Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:00) Yerevan', 'Caucasus Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+04:30) Kabul', 'Afghanistan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+05:00) Ashgabat, Tashkent', 'West Asia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+05:00) Islamabad, Karachi', 'Pakistan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', 'India Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+05:30) Sri Jayawardenepura', 'Sri Lanka Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+05:45) Kathmandu', 'Nepal Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+06:00) Astana', 'Central Asia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+06:00) Dhaka', 'Bangladesh Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+06:00) Ekaterinburg', 'Ekaterinburg Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+06:30) Yangon (Rangoon)', 'Myanmar Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+07:00) Bangkok, Hanoi, Jakarta', 'SE Asia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+07:00) Novosibirsk', 'N. Central Asia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', 'China Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Krasnoyarsk', 'North Asia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Kuala Lumpur, Singapore', 'Singapore Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Perth', 'W. Australia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Taipei', 'Taipei Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+08:00) Ulaanbaatar', 'Ulaanbaatar Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+09:00) Irkutsk', 'North Asia East Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+09:00) Osaka, Sapporo, Tokyo', 'Tokyo Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+09:00) Seoul', 'Korea Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+09:30) Adelaide', 'Cen. Australia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+09:30) Darwin', 'AUS Central Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+10:00) Brisbane', 'E. Australia Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+10:00) Canberra, Melbourne, Sydney', 'AUS Eastern Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+10:00) Guam, Port Moresby', 'West Pacific Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+10:00) Hobart', 'Tasmania Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+10:00) Yakutsk', 'Yakutsk Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+11:00) Solomon Is., New Caledonia', 'Central Pacific Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+11:00) Vladivostok', 'Vladivostok Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+12:00) Auckland, Wellington', 'New Zealand Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+12:00) Coordinated Universal Time+12', 'UTC+12')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+12:00) Fiji', 'Fiji Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+12:00) Magadan', 'Magadan Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+12:00) Petropavlovsk-Kamchatsky - Old', 'Kamchatka Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+13:00) Nuku''alofa', 'Tonga Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+13:00) Samoa', 'Samoa Standard Time')
INSERT INTO  [TimeZone]([Name], [TimeZoneInfoId]) values( '(UTC+14:00) Kiritimati Island', 'Line Islands Standard Time')
