//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSender.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HsbcMails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HsbcMails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailSender.Resources.HsbcMails", typeof(HsbcMails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///   &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Activation of Your Account&lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AccountActivationBody {
            get {
                return ResourceManager.GetString("AccountActivationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of Your Account.
        /// </summary>
        public static string AccountActivationSubject {
            get {
                return ResourceManager.GetString("AccountActivationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FileFormatIncorrectMailBody {
            get {
                return ResourceManager.GetString("FileFormatIncorrectMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file Format.
        /// </summary>
        public static string FileFormatIncorrectMailSubject {
            get {
                return ResourceManager.GetString("FileFormatIncorrectMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImportSuccessMailBody {
            get {
                return ResourceManager.GetString("ImportSuccessMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSBC Users imported successfully..
        /// </summary>
        public static string ImportSuccessMailSubject {
            get {
                return ResourceManager.GetString("ImportSuccessMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InvalidFileExtensionBody {
            get {
                return ResourceManager.GetString("InvalidFileExtensionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension..
        /// </summary>
        public static string InvalidFileExtensionSubject {
            get {
                return ResourceManager.GetString("InvalidFileExtensionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NoMailOrAttachmentMailBody {
            get {
                return ResourceManager.GetString("NoMailOrAttachmentMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Found.
        /// </summary>
        public static string NoMailOrAttachmentMailSubject {
            get {
                return ResourceManager.GetString("NoMailOrAttachmentMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///     &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;Your free trial offer expires in 10 Days!&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubscriptionExpirationAlertBody {
            get {
                return ResourceManager.GetString("SubscriptionExpirationAlertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Gift from the Humane Society is About to Expire!.
        /// </summary>
        public static string SubscriptionExpirationAlertSubject {
            get {
                return ResourceManager.GetString("SubscriptionExpirationAlertSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;&lt;font size=&quot;6&quot;&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/font&gt;&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SupportUserSubscriptionBody {
            get {
                return ResourceManager.GetString("SupportUserSubscriptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Registered User – Registered by Activ4Pets Team.
        /// </summary>
        public static string SupportUserSubscriptionByA4PMailSubject {
            get {
                return ResourceManager.GetString("SupportUserSubscriptionByA4PMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///     &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Congratulations on the adoption of your pet!&lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations on the adoption of your pet!.
        /// </summary>
        public static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
    }
}
