//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSender.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmailSender.Resources.NotificationMails", typeof(NotificationMails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Your pet’s insurance is about to expire&lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br / [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsuranceBody {
            get {
                return ResourceManager.GetString("InsuranceBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;ActivAnimo&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 01 47 57 65 97&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Your pet’s insurance is about to expire&lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br / [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsuranceBody_langFR {
            get {
                return ResourceManager.GetString("InsuranceBody_langFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet’s insurance is about to expire.
        /// </summary>
        public static string InsuranceSubject {
            get {
                return ResourceManager.GetString("InsuranceSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pet’s insurance is about to expire.
        /// </summary>
        public static string InsuranceSubject_langFR {
            get {
                return ResourceManager.GetString("InsuranceSubject_langFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Medication Alert &lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MedicationBody {
            get {
                return ResourceManager.GetString("MedicationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;ActivAnimo&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 01 47 57 65 97&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///    &lt;font size=&quot;6&quot;&gt;&lt;b&gt;Medication Alert &lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot;Arial&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MedicationBody_langFR {
            get {
                return ResourceManager.GetString("MedicationBody_langFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Alert.
        /// </summary>
        public static string MedicationSubject {
            get {
                return ResourceManager.GetString("MedicationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication Alert.
        /// </summary>
        public static string MedicationSubject_langFR {
            get {
                return ResourceManager.GetString("MedicationSubject_langFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;Activ4Pets&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;        
        ///		&lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 1-888-51-ACTIV (22848)&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///	&lt;font size=&quot;6&quot;&gt;&lt;b&gt; Friendly Reminder Alert &lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;fon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReminderBody {
            get {
                return ResourceManager.GetString("ReminderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td align=&quot;left&quot;&gt;
        ///            &lt;img src=&quot;{0}&quot; alt=&quot;ActivAnimo&quot; style=&quot;display: block;&quot; /&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;/td&gt;        
        ///		&lt;td align=&quot;right&quot;&gt;&lt;font face=&quot;Arial&quot; size=&quot;2&quot;&gt;Need to ask a question? &lt;b&gt;Call 01 47 57 65 97&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;
        ///&lt;hr style=&quot;background-color: #444; border-width: 0; color: #444; height: 2px;&quot;&gt;
        ///&lt;br /&gt;
        ///&lt;div style=&quot;margin-left: -2px;&quot;&gt;
        ///	&lt;font size=&quot;6&quot;&gt;&lt;b&gt; Friendly Reminder Alert &lt;/b&gt;&lt;/font&gt;
        ///&lt;/div&gt;
        ///&lt;br /&gt;
        ///&lt;br /&gt;
        ///&lt;font face=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReminderBody_langFR {
            get {
                return ResourceManager.GetString("ReminderBody_langFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Reminder Alert.
        /// </summary>
        public static string ReminderSubject {
            get {
                return ResourceManager.GetString("ReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Reminder Alert.
        /// </summary>
        public static string ReminderSubject_langFR {
            get {
                return ResourceManager.GetString("ReminderSubject_langFR", resourceCulture);
            }
        }
    }
}
