//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetFoodPlan
    {
        public PetFoodPlan()
        {
            this.Comment = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int PetId { get; set; }
        public string FoodName { get; set; }
        public Nullable<bool> IsRecomended { get; set; }
        public Nullable<bool> IsForbiden { get; set; }
        public bool IsDeleted { get; set; }
    
        public EncryptedText Comment { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
