//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionService
    {
        public SubscriptionService()
        {
            this.UserSubscriptions = new HashSet<UserSubscription>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AditionalPetCount { get; set; }
        public Nullable<int> AditionalSMOCount { get; set; }
        public Nullable<int> AditionalMRACount { get; set; }
        public Nullable<int> AditionalECCount { get; set; }
    
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
    }
}
