//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int Id { get; set; }
        public Nullable<int> UserSubscriptionId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<int> TransactionResultId { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> BillingInformationId { get; set; }
    
        public virtual TransactionResult TransactionResult { get; set; }
        public virtual UserSubscription UserSubscription { get; set; }
        public virtual BillingInformation BillingInformation { get; set; }
    }
}
