//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int Id { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public string AddressIP { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string TargetTableName { get; set; }
        public string TargetTableId { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public Nullable<int> TargetPetId { get; set; }
        public Model.AuditModificationTypeEnum AuditModificationTypeId { get; set; }
        public string XMLData { get; set; }
    
        public virtual AuditModificationType AuditModificationType { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
