use ADOPets_Rev

ALTER TABLE SubscriptionService
ADD AditionalECCount int NULL

ALTER TABLE SubscriptionService
Drop FK_SubscriptionService_SubscriptionBase

ALTER TABLE SubscriptionService
Drop FK_SubscriptionService_UserSubscription

ALTER TABLE SubscriptionService
drop column SubscriptionId

ALTER TABLE SubscriptionService
drop column UserSubscriptionId
