//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EconsultationSummary
    {
        public decimal ID { get; set; }
        public Nullable<int> EConsultationId { get; set; }
        public Nullable<int> VetId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateSummary { get; set; }
        public string FilesFolder { get; set; }
        public string FilesName { get; set; }
        public Nullable<int> EconsultationStatusId { get; set; }
        public string CenterID { get; set; }
        public string PetName { get; set; }
        public string PetDOB { get; set; }
        public string EconsultationDateTime { get; set; }
        public Nullable<decimal> EconsultationDuration { get; set; }
        public string Diagnoses { get; set; }
        public string Treatment { get; set; }
        public Nullable<int> FollowUp { get; set; }
        public string VeterianFirstName { get; set; }
        public string VeterianMiddleName { get; set; }
        public string VeterianLastName { get; set; }
        public string VeterianSignature { get; set; }
        public string Remark { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
