//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Subject = new EncryptedText();
            this.Body = new EncryptedText();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FromUserId { get; set; }
        public int ToUserId { get; set; }
        public System.DateTime Date { get; set; }
        public Model.MessageTypeEnum MessageTypeId { get; set; }
        public bool Unread { get; set; }
        public string ConversationId { get; set; }
    
        public EncryptedText Subject { get; set; }
        public EncryptedText Body { get; set; }
    
        public virtual MessageType MessageType { get; set; }
        public virtual User User { get; set; }
        public virtual User UserFrom { get; set; }
        public virtual User UserTo { get; set; }
    }
}
