//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADOPets.Web.Resources.Econsultation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Add {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Add() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADOPets.Web.Resources.Econsultation.Add", typeof(Add).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address 1.
        /// </summary>
        public static string Address1PlaceHolder {
            get {
                return ResourceManager.GetString("Address1PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1 is required.
        /// </summary>
        public static string Address1Required {
            get {
                return ResourceManager.GetString("Address1Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address 2.
        /// </summary>
        public static string Address2PlaceHolder {
            get {
                return ResourceManager.GetString("Address2PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully raised ECONSULTATION for your pet..
        /// </summary>
        public static string AddSuccessfullMessage {
            get {
                return ResourceManager.GetString("AddSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to e-consultation.
        /// </summary>
        public static string AgreeTerms {
            get {
                return ResourceManager.GetString("AgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Veterinarian.
        /// </summary>
        public static string AssignVet {
            get {
                return ResourceManager.GetString("AssignVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign a Veterinarian.
        /// </summary>
        public static string AssignVetRequired {
            get {
                return ResourceManager.GetString("AssignVetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to E-Consultation.
        /// </summary>
        public static string BackEconsultation {
            get {
                return ResourceManager.GetString("BackEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Country.
        /// </summary>
        public static string BillingCountry {
            get {
                return ResourceManager.GetString("BillingCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        public static string BillingInformation {
            get {
                return ResourceManager.GetString("BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing State.
        /// </summary>
        public static string BillingState {
            get {
                return ResourceManager.GetString("BillingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number should be a number.
        /// </summary>
        public static string CardRequiredNumber {
            get {
                return ResourceManager.GetString("CardRequiredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Type.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        public static string CityPlaceHolder {
            get {
                return ResourceManager.GetString("CityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reviewed and confirm that my Pet&apos;s medical records are current..
        /// </summary>
        public static string ConfirmMedicalRecords {
            get {
                return ResourceManager.GetString("ConfirmMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string ConsultationCountryRequired {
            get {
                return ResourceManager.GetString("ConsultationCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Date.
        /// </summary>
        public static string ConsultationDatePlaceHolder {
            get {
                return ResourceManager.GetString("ConsultationDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of consultation is required.
        /// </summary>
        public static string ConsultationDayRequired {
            get {
                return ResourceManager.GetString("ConsultationDayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Time.
        /// </summary>
        public static string ConsultationTimePlaceHolder {
            get {
                return ResourceManager.GetString("ConsultationTimePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of consultation is required.
        /// </summary>
        public static string ConsultationTImeRequired {
            get {
                return ResourceManager.GetString("ConsultationTImeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the best way to contact you?.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contact Type.
        /// </summary>
        public static string ContactTypePlaceHolder {
            get {
                return ResourceManager.GetString("ContactTypePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where will you be located during this consultation?.
        /// </summary>
        public static string CountryOfEconsultation {
            get {
                return ResourceManager.GetString("CountryOfEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string CountryPlaceHolder {
            get {
                return ResourceManager.GetString("CountryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid Credit Card.
        /// </summary>
        public static string CreaditCardValidation {
            get {
                return ResourceManager.GetString("CreaditCardValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Credit Card Number.
        /// </summary>
        public static string CreditCardNumberPlaceHolder {
            get {
                return ResourceManager.GetString("CreditCardNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number is Required.
        /// </summary>
        public static string CreditCardNumberRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Type.
        /// </summary>
        public static string CreditCardType {
            get {
                return ResourceManager.GetString("CreditCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card Type.
        /// </summary>
        public static string CreditCardTypePlaceHolder {
            get {
                return ResourceManager.GetString("CreditCardTypePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Type is Required.
        /// </summary>
        public static string CreditCardTypeRequired {
            get {
                return ResourceManager.GetString("CreditCardTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cvv Number.
        /// </summary>
        public static string CVVPlaceHolder {
            get {
                return ResourceManager.GetString("CVVPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Number is Required.
        /// </summary>
        public static string CVVRequired {
            get {
                return ResourceManager.GetString("CVVRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV should be a Number.
        /// </summary>
        public static string CVVRequiredNumber {
            get {
                return ResourceManager.GetString("CVVRequiredNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What day would you like to have your consult?.
        /// </summary>
        public static string DayOfEconsultation {
            get {
                return ResourceManager.GetString("DayOfEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC ID.
        /// </summary>
        public static string EC_ID {
            get {
                return ResourceManager.GetString("EC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EconsultationStatus.
        /// </summary>
        public static string EconsultationStatus {
            get {
                return ResourceManager.GetString("EconsultationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to the Veterinarian Expert to review your request..
        /// </summary>
        public static string EmailMsg {
            get {
                return ResourceManager.GetString("EmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Expiration Date.
        /// </summary>
        public static string ExpirationDatePlaceHolder {
            get {
                return ResourceManager.GetString("ExpirationDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date is required.
        /// </summary>
        public static string ExpirationDateRequired {
            get {
                return ResourceManager.GetString("ExpirationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Insurance_Add_Phone {
            get {
                return ResourceManager.GetString("Insurance_Add_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Phone Number.
        /// </summary>
        public static string Insurance_Add_PhonNumberFormat {
            get {
                return ResourceManager.GetString("Insurance_Add_PhonNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Invalidemail {
            get {
                return ResourceManager.GetString("Invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        public static string InValidPhone {
            get {
                return ResourceManager.GetString("InValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction has been approved.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep1 {
            get {
                return ResourceManager.GetString("NextStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string Order_Number {
            get {
                return ResourceManager.GetString("Order_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the Pet condition?.
        /// </summary>
        public static string PetCondition {
            get {
                return ResourceManager.GetString("PetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pet Condition.
        /// </summary>
        public static string PetConditionPlaceHolder {
            get {
                return ResourceManager.GetString("PetConditionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pet Condition.
        /// </summary>
        public static string PetConditionPlaceHolder1 {
            get {
                return ResourceManager.GetString("PetConditionPlaceHolder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet condition is required.
        /// </summary>
        public static string PetConditionRequired {
            get {
                return ResourceManager.GetString("PetConditionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Name.
        /// </summary>
        public static string PetName {
            get {
                return ResourceManager.GetString("PetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pet Name.
        /// </summary>
        public static string PetNamePlaceHolder {
            get {
                return ResourceManager.GetString("PetNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet name is required.
        /// </summary>
        public static string PetNameRequired {
            get {
                return ResourceManager.GetString("PetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Type.
        /// </summary>
        public static string PetType {
            get {
                return ResourceManager.GetString("PetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone.
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchese {
            get {
                return ResourceManager.GetString("Purchese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Permanent Address?.
        /// </summary>
        public static string SamePermanantAddress {
            get {
                return ResourceManager.GetString("SamePermanantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChange.
        /// </summary>
        public static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select current vet.
        /// </summary>
        public static string SelectCurrentVet {
            get {
                return ResourceManager.GetString("SelectCurrentVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pet.
        /// </summary>
        public static string SelectPet {
            get {
                return ResourceManager.GetString("SelectPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send the consultation info to your current vet?.
        /// </summary>
        public static string SendInfoToVet {
            get {
                return ResourceManager.GetString("SendInfoToVet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service charge - $25 for one e-consultation service.
        /// </summary>
        public static string ServiceCharge {
            get {
                return ResourceManager.GetString("ServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Information.
        /// </summary>
        public static string SetupInformation {
            get {
                return ResourceManager.GetString("SetupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string StatePlaceHolder {
            get {
                return ResourceManager.GetString("StatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        public static string StateRequired {
            get {
                return ResourceManager.GetString("StateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Econsultation Status is required.
        /// </summary>
        public static string StatusRequiredField {
            get {
                return ResourceManager.GetString("StatusRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms1.
        /// </summary>
        public static string Symptoms1 {
            get {
                return ResourceManager.GetString("Symptoms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Symptoms 1.
        /// </summary>
        public static string Symptoms1PlaceHolder {
            get {
                return ResourceManager.GetString("Symptoms1PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms2.
        /// </summary>
        public static string Symptoms2 {
            get {
                return ResourceManager.GetString("Symptoms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Symptoms 2.
        /// </summary>
        public static string Symptoms2PlaceHolder {
            get {
                return ResourceManager.GetString("Symptoms2PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms3.
        /// </summary>
        public static string Symptoms3 {
            get {
                return ResourceManager.GetString("Symptoms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe Symptoms 3.
        /// </summary>
        public static string Symptoms3PlaceHolder {
            get {
                return ResourceManager.GetString("Symptoms3PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe 3 key symptoms the Pet is experiencing.
        /// </summary>
        public static string SymptomsOfPet {
            get {
                return ResourceManager.GetString("SymptomsOfPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions..
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time would you like to have your consult?.
        /// </summary>
        public static string TimeOfEconsultation {
            get {
                return ResourceManager.GetString("TimeOfEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time zone you will be in during this consultation?.
        /// </summary>
        public static string TimeZoneOfEconsultation {
            get {
                return ResourceManager.GetString("TimeZoneOfEconsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TimeZone.
        /// </summary>
        public static string TimeZonePlaceHolder {
            get {
                return ResourceManager.GetString("TimeZonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone is required.
        /// </summary>
        public static string TimeZoneRequired {
            get {
                return ResourceManager.GetString("TimeZoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New E-Consultation.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TryAgain.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Zip.
        /// </summary>
        public static string ZipPlaceHolder {
            get {
                return ResourceManager.GetString("ZipPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip is required.
        /// </summary>
        public static string ZipRequired {
            get {
                return ResourceManager.GetString("ZipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip should be a number.
        /// </summary>
        public static string ZipRequiredNumber {
            get {
                return ResourceManager.GetString("ZipRequiredNumber", resourceCulture);
            }
        }
    }
}
