//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareCategoryTypeContact
    {
        public int Id { get; set; }
        public int ShareContactId { get; set; }
        public Model.ShareCategoryTypeEnum ShareCategoryTypeId { get; set; }
        public Nullable<int> PetId { get; set; }
    
        public virtual ShareCategoryType ShareCategoryType { get; set; }
        public virtual ShareContact ShareContact { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
