//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.PartnerSubscriptions = new HashSet<PartnerSubscription>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.Customizations = new HashSet<Customization>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PartnerTypeId { get; set; }
        public string Email { get; set; }
        public string SiteWeb { get; set; }
        public string Phone { get; set; }
    
        public virtual PartnerType PartnerType { get; set; }
        public virtual ICollection<PartnerSubscription> PartnerSubscriptions { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<Customization> Customizations { get; set; }
    }
}
