//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPrescription
    {
        public int Id { get; set; }
        public Nullable<int> EcId { get; set; }
        public Nullable<System.DateTime> DatePrescription { get; set; }
        public string FilesID { get; set; }
        public int PrescriptionsStatus { get; set; }
        public string PrescriptionContent { get; set; }
        public Nullable<int> Label { get; set; }
        public Nullable<decimal> Refill { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Voluntary { get; set; }
        public string MedXPTitle1 { get; set; }
        public string MedXPTitle2 { get; set; }
        public string DEA { get; set; }
        public string NPI { get; set; }
        public string PrescriptionTitle { get; set; }
        public int TypePrescription { get; set; }
        public string RPPS { get; set; }
    
        public virtual EConsultation EConsultation { get; set; }
    }
}
