//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareCategoryType
    {
        public ShareCategoryType()
        {
            this.ShareCategoryTypeContacts = new HashSet<ShareCategoryTypeContact>();
            this.SharePetInformations = new HashSet<SharePetInformation>();
        }
    
        public Model.ShareCategoryTypeEnum Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ShareCategoryTypeContact> ShareCategoryTypeContacts { get; set; }
        public virtual ICollection<SharePetInformation> SharePetInformations { get; set; }
    }
}
