//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumGallery_Photo
    {
        public int Id { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public bool IsDefaultAlbumCover { get; set; }
    
        public virtual AlbumGallery AlbumGallery { get; set; }
        public virtual Gallery Gallery { get; set; }
    }
}
